#!/bin/bash

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
xdg-desktop-menu install /usr/share/applications/avalonia-atomex.desktop
xdg-mime default avalonia-atomex.desktop x-scheme-handler/atomex
